### PR TITLE
Multithreading traits

### PR DESCRIPTION
**Pull request by arduano**
I was unable to use simdeez in my multithreaded application without adding these.

It does not appear to break simdeez in any way.

### CODE REVIEW

**Review by verpeteren — APPROVED** [review]
I made a very simple test with spawn and it seems to work
```
xtern crate simdeez;

#[cfg(test)]
mod tests {
    use simdeez::avx2::*;
    use simdeez::scalar::*;
    use simdeez::sse2::*;
    use simdeez::sse41::*;
    use std::ops::Mul;
    use std::thread::spawn;

    simd_runtime_generate!(
        fn impl_simple_test_build(a : &[f32], b: &[f32], c: &[f32]) {
            let sa = S::loadu_ps(&a[0]);
            let sb = S::loadu_ps(&b[0]);
            let r = sa.mul(sb);
            assert_eq!(r[0], c[0]);
            assert_eq!(r[1], c[1]);
            assert_eq!(r[2], c[2]);
            assert_eq!(r[3], c[3]);
        }
    );

    #[test]
    fn simple_test() {
        let a = vec![1.0, 2.11, 3.2, 4.3];
        let b = vec![1.9, 2.82, 3.7, 4.8];
        let c = vec![1.9, 5.9501996, 11.84, 20.640001];
        for _i in 0..8 {
            let ac = a.clone();
            let bc = b.clone();
            let cc = c.clone();
            spawn(move ||  {
                impl_simple_test_build_runtime_select(ac.as_slice(), bc.as_slice(), cc.as_slice());
                }
            );
        }
    }
}
```

I also tested this branch as a dependency with the `evolution` application and that also works fine.

**Comment by arduano** [comment]
My main use case was using the Simd trait as a generic on other structs which must implement Sync.

Basically, I made a SIMD-oriented audio pipeline system where there is a common "sample generator" trait that returns 1 SIMD sample at a time, and the sample generators can be mixed and matched to create the desired pipeline at compile time.

They needed to be Sync, and because they had `<S: Simd>` Rust expects S to be Sync as well. I could have added `<S: Simd + Send + Sync + 'static>` on each one but that would be unnecessary when this PR's solution makes sense anyway.

**Comment by jackmott** [comment]
merging this.  @arduano, are you interested in taking over this repository? I don't have time to be a proper maintainer anymore, so if you would like to take over, I can hand it off to you.

**Comment by arduano** [comment]
@jackmott yeah I'd be happy with that!

**Comment by arduano** [comment]
Though I'm about to leave somewhere for today, so if I don't respond soon then I'll be back near the end of the day.

**Comment by arduano** [comment]
@jackmott Hey, just following up, are you still interested in letting me take over?

**Comment by jackmott** [comment]
Yep, do you currently have any forks of the repo? If so it won't let me transfer owership to you.

**Comment by arduano** [comment]
Just deleted it

**Comment by jackmott** [comment]
request should be in

**Comment by arduano** [comment]
Could you please pass me crates.io ownership too?

**Comment by arduano** [comment]
@jackmott Hey, just bumping about the above again in case you only get notified by mentions

**Comment by jackmott** [comment]
@arduano same username there?

**Comment by arduano** [comment]
yeah

**Comment by jackmott** [comment]
ok you should have an invite

**Comment by arduano** [comment]
thank you, I've accepted

**Comment by jackmott** [comment]
Allright, it is all up to you know, do great things! thanks

**Pull request merged**
